tt1 = [
  ["CSE1","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","PH 2102 (T) (E-CR8)","MA 2103 (T) (E-CR8)","Lunch","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","French-III HS 2103 (T) (E-CR7)","FREE"],
  ["CSE2","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","PH 2102 (T) (E-CR10)","MA 2103 (T) (E-CR10)","Lunch","Data Structures (P) (CS Lab - 1)","Data Structures (P) (CS Lab - 1)","French-III HS 2103 (T) (E-CR9)","FREE"],
  ["CSE3","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","PH 2102 (T) (E-CR12)","MA 2103 (T) (E-CR12)","Lunch","EE 2101 (T) (E-CR8)","French-III HS 2103 (T) (E-CR11)","FREE","FREE"],
  ["CSE4","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","PH 2102 (T) (E-CR14)","MA 2103 (T) (E-CR14)","Lunch","EE 2101 (T) (E-CR10)","French-III HS 2103 (T) (E-CR13)","FREE","FREE"],
  ["CM","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Data Structures (P) (CS Lab - 1)","Data Structures (P) (CS Lab - 1)","French-III HS 2103 (T) (E-CR7)","Lunch","Real Analysis (MA2104)(L) (E-TR3)","Graph Algorithms (MA2105) (L) (E-TR4)"," MA 2103 (T) (E-CR16)","FREE"],
  ["ECE1","Analog and Digital Circuits (EC 2101) (P)","Analog and Digital Circuits (EC 2101) (P)","Data Structures (P) (CS Lab - 1)","Data Structures (P) (CS Lab - 1)","French-III HS 2103 (T) (E-CR7)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4"," MA 2103 (T) (E-CR16)","FREE"],
  ["ECE2","FREE","FREE","Analog and Digital Circuits (EC 2101) (P)","Analog and Digital Circuits (EC 2101) (P)","French-III HS 2103 (T) (E-CR9)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","MA 2103 (T) (E-TR3)","FREE"],
  ["AI1","   MA 2103 (T) (E-CR8)","French-III HS 2103 (T) (E-CR7)","CS 2104 (T) (E-CR8)","EE 2101 (T) (E-CR11)","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR8)","FREE"],
  ["AI2","   MA 2103 (T) (E-CR10)","French-III HS 2103 (T) (E-CR9)","CS 2104 (T) (E-CR10)","EE 2101 (T) (E-CR12)","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR10)","FREE"],
  ["AI3","   MA 2103 (T) (E-CR12)","French-III HS 2103 (T) (E-CR11)","CS 2104 (T) (E-CR12)","FREE","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR12)","FREE"],
  ["CE"," MA 2103 (T) (E-CR14)","French-III HS 2103 (T) (E-CR13)"," CS 2104 (T) (E-CR14)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR14)","FREE"],
  ["ME"," MA 2103 (T) (E-CR14)","French-III HS 2103 (T) (E-CR13)"," CS 2104 (T) (E-CR14)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR14)","FREE"],
  ["MT"," MA 2103 (T) (E-CR14)","French-III HS 2103 (T) (E-CR13)"," CS 2104 (T) (E-CR14)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR14)","FREE"],
  ["NT"," MA 2103 (T) (E-CR14)","French-III HS 2103 (T) (E-CR13)"," CS 2104 (T) (E-CR14)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Lunch","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","PH 2102 (T) (E-CR14)","FREE"],
  ["CSE1","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","French-III HS 2103 (T) (E-CR7)","EE 2101 (T) (E-CR8)","Lunch","Physics-II       (PH 2102 ) (E-LT3)","Data Structures (P) (Language Lab)","Data Structures (P) (Language Lab)","FREE"],
  ["CSE2","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","French-III HS 2103 (T) (E-CR9)","EE 2101 (T) (E-CR10)","Lunch","Physics-II       (PH 2102 ) (E-LT3)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","FREE"],
  ["CSE3","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Lunch","Physics-II       (PH 2102 ) (E-LT3)","French-III HS 2103 (T) (E-CR7)","FREE","FREE"],
  ["CSE4","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","Lunch","Physics-II       (PH 2102 ) (E-LT3)","French-III HS 2103 (T) (E-CR9)","FREE","FREE"],
  ["CM ","Data Structures (CS 2104) (L)    E-LT4","Maths-III         (MA 2103 ) E-LT4","EE 2101 (T) (E-CR8)","French-III HS 2103 (T) (E-CR11)","Real Analysis (MA2104)(L) (E-TR3)","Lunch","Physics-II       (PH 2102 ) (E-LT3)","French-III HS 2103 (T) (E-CR11)","Graph Algorithms (MA2105) (L) (E-TR4)","FREE"],
  ["ECE1","Analog and Digital Circuits (EC 2101) (L) (E-CR13)","FREE","EE 2101 (T) (E-CR8)","French-III HS 2103 (T) (E-CR11)","Physics-II       (PH 2102) (E-LT3)","Lunch","Discrete Mathematics (EC 2103) (L) (E-CR7)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["ECE2","Analog and Digital Circuits (EC 2101) (L) (E-CR13)","FREE","EE 2101 (T) (E-CR10)","French-III HS 2103 (T) (E-CR13)","Physics-II       (PH 2102) (E-LT3)","Lunch","Discrete Mathematics (EC 2103) (L) (E-CR7)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["AI1","FREE","FREE","French-III HS 2103 (T) (E-CR7)","FREE","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["AI2","FREE","FREE","French-III HS 2103 (T) (E-CR9)","FREE","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["AI3","FREE","EE 2101 (T) (E-CR15)","French-III HS 2103 (T) (E-CR11)","FREE","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["CE","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","French-III HS 2103 (T) (E-CR13)","Mechanics of Materials (CE 2103)(L) (E-TR4)","Physics-II       (PH 2102) (E-LT3)","Lunch","Mechanics of Materials (CE 2103)(T)) (E-TR4)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["ME","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","French-III HS 2103 (T) (E-CR13)","Introduction to Materials Sciences \n(ME 2107)(L) (E-TR1)","Physics-II       (PH 2102) (E-LT3)","Lunch","Thermal Engineering (ME 2115)(T) (E-TR1)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["MT","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","French-III HS 2103 (T) (E-CR13)","Introduction to Materials Sciences \n(ME 2107)(L) (E-TR1)","Physics-II       (PH 2102) (E-LT3)","Lunch","MT 2101 (T) (E-TR2)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["NT","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","French-III HS 2103 (T) (E-CR13)","Introduction to Materials Science (PH 2103) (L) (E-TR3)","Physics-II       (PH 2102) (E-LT3)","Lunch","Introduction to Nano-technology and Science (CH 2103)(L) (E-TR3)","Maths-III         (MA 2103) E-LT4","Data Structures (CS 2104) (L)    E-LT4","FREE"],
  ["CSE1","Data Structures (CS 2104) (T) (E-CR8)","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","FREE","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CSE2","Data Structures (CS 2104) (T) (E-CR10)","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","FREE","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CSE3","Data Structures (CS 2104) (T) (E-CR12)","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","FREE","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CSE4","Data Structures (CS 2104) (T) (E-CR14)","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","FREE","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CM ","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Signals and Systems        (EE 2101) (L) (E-LT4)","Algebra (MA2106) (L) (E-TR3)","Real Analysis (MA2104)(L) (E-TR3)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["ECE1","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["ECE2","Data Structures  (P) (CS Lab-1)","Data Structures  (P) (CS Lab-1)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["AI1","FREE","FREE","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["AI2","FREE","FREE","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["AI3","FREE","FREE","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CE","Mechanics of Materials (CE 2103)(L) (E-TR4)","Building Drawing (CE 2104) (P)","Building Drawing (CE 2104) (P)","FREE","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["ME","FREE","Thermal Engineering (ME 2115)(L) (E-TR1)","Introduction to Materials Sciences (ME 2107)(P)","Introduction to Materials Sciences (ME 2107)(P)","FREE","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["MT","FREE","FREE","Introduction to Materials Sciences (ME 2107)(P)","Introduction to Materials Sciences (ME 2107)(P)","Signals and Systems        (MT 2101) (L) (E-TR1)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["NT","Biology (BI 2101)(P) (E-TR3)","Introduction to Materials Science (PH 2103) (L) (E-TR3)","Introduction to Nano-technology and Science (CH 2103)(L) (E-TR3)","Introduction to Materials Science (PH 2103) (P)","Introduction to Materials Science (PH 2103) (P)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
  ["CSE1","Maths-III         (MA 2103 ) (E-LT4)","Signals and Systems (EE 2101) (L) (E-LT4)","Principles of Economics     (HS 2102) (L) (E-LT4)","Optimization Techniques for AI (CS/AI 2101(L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-8)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CSE2","Maths-III         (MA 2103 ) (E-LT4)","Signals and Systems (EE 2101) (L) (E-LT4)","Principles of Economics     (HS 2102) (L) (E-LT4)","Optimization Techniques for AI (CS/AI 2101(L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-10)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CSE3","Maths-III         (MA 2103 ) (E-LT4)","Signals and Systems (EE 2101) (L) (E-LT4)","Principles of Economics     (HS 2102) (L) (E-LT4)","Optimization Techniques for AI (CS/AI 2101(L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-12)","Lunch","Physics-II       (PH 2102) (E-LT3)","Data Structures  (P) (CS Lab-1)","Data Structures  (P) (CS Lab-1)","FREE"],
  ["CSE4","Maths-III         (MA 2103 ) (E-LT4)","Signals and Systems (EE 2101) (L) (E-LT4)","Principles of Economics     (HS 2102) (L) (E-LT4)","Optimization Techniques for AI (CS/AI 2101(L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-14)","Lunch","Physics-II       (PH 2102) (E-LT3)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","FREE"],
  ["CM ","Maths-III         (MA 2103 ) (E-LT4)","Signals and Systems (EE 2101) (L) (E-LT4)","Principles of Economics     (HS 2102) (L) (E-LT4)","PH 2102 (T) (E-CR8)","FREE","Lunch","Physics-II       (PH 2102) (E-LT3)","Algebra (MA2106) (L) (E-TR3)","Graph Algorithms (MA2105) (L) (E-TR4)","Data Structures (CS 2104) (T) (ECR-8)"],
  ["ECE1","FREE","FREE","Discrete Mathematics (EC 2103) (L) (E-CR7)","PH 2102 (T) (E-CR8)","Physics-II       (PH 2102) (E-LT3)","Lunch","Analog and Digital Circuits (EC 2101) (L) (E-CR13)","Maths-III         (MA 2103) E-LT4","Signals and Systems        (EE 2101) (L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-8)"],
  ["ECE2","FREE","FREE","Discrete Mathematics (EC 2103) (L) (E-CR7)","PH 2102 (T) (E-CR10)","Physics-II       (PH 2102) (E-LT3)","Lunch","Analog and Digital Circuits (EC 2101) (L) (E-CR13)","Maths-III         (MA 2103) E-LT4","Signals and Systems        (EE 2101) (L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-10)"],
  ["AI1","FREE","FREE","Data Structures  (P) (CS Lab-1)","Data Structures  (P) (CS Lab-1)","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Signals and Systems        (EE 2101) (L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-12)"],
  ["AI2","FREE","FREE","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Signals and Systems        (EE 2101) (L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-14)"],
  ["AI3","FREE","FREE","FREE","FREE","Physics-II       (PH 2102) (E-LT3)","Lunch","Optimization Techniques for AI (CS/AI 2101)(L) (E-LT4)","Maths-III         (MA 2103) E-LT4","Signals and Systems        (EE 2101) (L) (E-LT4)","Data Structures (CS 2104) (T) (ECR-16)"],
  ["CE","FREE","FREE","Mechanics of Materials (CE 2103)(L) (E-TR4)","Data Structures (CS 2104) (T) (ECR-16)","Physics-II       (PH 2102) (E-LT3)","Lunch","FREE","Maths-III         (MA 2103) E-LT4","FREE","FREE"],
  ["ME","FREE","FREE","Thermal Engineering (ME 2115)(L) (E-TR1)","Data Structures (CS 2104) (T) (ECR-16)","Physics-II       (PH 2102) (E-LT3)","Lunch","PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Maths-III         (MA 2103) E-LT4","PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","FREE"],
  ["MT","FREE","FREE","FREE","Data Structures (CS 2104) (T) (ECR-16)","Physics-II       (PH 2102) (E-LT3)","Lunch","FREE","Maths-III         (MA 2103) E-LT4","Signals and Systems        (MT 2101) (L) (E-TR1)","FREE"],
  ["NT","FREE","FREE","Biology (BI 2101)(P) (E-TR3)","Data Structures (CS 2104) (T) (ECR-16)","Physics-II       (PH 2102) (E-LT3)","Lunch","Introduction to Materials Science (PH 2103) (L) (E-TR3)","Maths-III         (MA 2103) E-LT4","Introduction to Nano-technology and Science (CH 2103)(L) (E-TR3)","FREE"],
  ["CSE1","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CSE2","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CSE3","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CSE4","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","FREE","FREE","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Physics-II       (PH 2102) (E-LT3)","FREE","FREE","FREE"],
  ["CM ","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Principles of Economics     (HS 2102) (E-LT3)/[Lean Start-up (HS 2101) (E-LT3); except CM]","Prog WS (R & GPU) (MA2107)(P) (Computer Lab - 2) (First Floor)","Prog WS (R & GPU) (MA2107)(P) (Computer Lab - 2) (First Floor)","Signals and Systems        (EE 2101) (L) (E-LT4)","Lunch","Physics-II       (PH 2102) (E-LT3)","Data Structures (CS 2104) (T) (ECR-8)","Algebra (MA2106) (L) (E-TR3)","FREE"],
  ["ECE1","FREE","Signals and Systems        (EE 2101)(L) (E-LT4)","FREE","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Data Structures (CS 2104) (T) (ECR-8)","FREE","FREE"],
  ["ECE2","FREE","Signals and Systems        (EE 2101)(L) (E-LT4)","FREE","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Data Structures (CS 2104) (T) (ECR-10)","FREE","FREE"],
  ["AI1","FREE","Signals and Systems        (EE 2101)(L) (E-LT4)","FREE","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","FREE"],
  ["AI2","FREE","Signals and Systems        (EE 2101)(L) (E-LT4)","Data Structures  (P) (CS Lab-1)","Data Structures  (P) (CS Lab-1)","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","FREE","FREE","FREE"],
  ["AI3","FREE","Signals and Systems        (EE 2101)(L) (E-LT4)","Physics-II (P) (Physics Lab)","Physics-II (P) (Physics Lab)","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Data Structures (P) (CS Lab-1)","Data Structures (P) (CS Lab-1)","FREE"],
  ["CE","FREE","Geology Lab (CE 2105) P","Geology Lab (CE 2105) P","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","Building Drawing (CE 2104) (P)","Building Drawing (CE 2104) (P)","FREE"],
  ["ME","FREE","Thermal Engineering (ME 2115)(L) (E-TR1)","Introduction to Materials Sciences (ME 2107)(L) (E-TR1)","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","FREE","FREE","FREE"],
  ["MT","FREE","FREE","Introduction to Materials Sciences (ME 2107)(L) (E-TR1)","Signals and Systems        (MT 2101)(L) (E-TR1)","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","FREE","FREE","FREE"],
  ["NT","FREE","Biology (BI 2101)(P) (E-TR3)","FREE","FREE","Physics-II       (PH 2102 ) (E-LT3)","Lunch","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4) / PDEs for Engineers (ME 2116) (only for ME later 7 weeks) (E-TR2)","FREE","FREE","FREE"],
  ["CSE1","FREE","FREE","FREE","FREE","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["CSE2","FREE","FREE","FREE","FREE","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["CSE3","FREE","FREE","FREE","FREE","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["CSE4","FREE","FREE","FREE","FREE","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["CM ","FREE","FREE","FREE","FREE","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","FREE"],
  ["ECE1","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","FREE"],
  ["ECE2","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4)  (Second Half of the Semester)","FREE"],
  ["AI1","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["AI2","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["AI3","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","FREE","FREE","FREE","FREE"],
  ["CE","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","FREE"],
  ["ME","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","FREE"],
  ["MT","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","FREE"],
  ["NT","FREE","FREE","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","Principles of Economics     (HS 2102) (L) (7 weeks) (E-LT4)/[Lean Start-up (HS 2101) (E-LT4) (For AI1/AI2/AI3) Second Half of the Semester]","FREE","Lunch","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","Lean Start-up (HS 2101) (E-LT4) (Second Half of the Semester)","FREE"]
];

tt2 = [
  [
    "CE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
    "CE 2203 L (Mechanics of Materials) (E-CR8)",
    "CE 2204 L (Engineering Surveying) (E-CR8)",
    "CE 2205 L(Fluid Mechanics) (E-CR8)",
    "CE 2206 L (Concrete Technology) (E-CR8)",
    "Lunch",
    "MA2208 Lab (LH11)",
    "MA2208 Lab (LH11)",
    "FREE",
  ],
  [
    "CS1",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python)(E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
  ],
  [
    "CS2",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python)(E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS3",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python)(E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "EE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE 2201 L (Digital Electronics (E-CR12)",
    "EE 2203 L (Linear Electronics) (E-CR12)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "EE 2207 L (Electromagnetic Waves) (E-CR12)",
    "Lunch",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "FREE",
  ],
  [
    "ECE1",
    "EC 2203 Digital System Design-Lab",
    "EC 2203 Digital System Design-Lab",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ECE2",
    "EC 2205 Communication Systems-Lab",
    "EC 2205 Communication Systems-Lab",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ME",
    "FREE",
    "ME 2204 L (Transport Phenomena) (E-CR14)",
    "ME 2205 L (Manufacturing Processes I) (E-CR14)",
    "ME 2206 L (Mechanics of Solids) (E-CR14)",
    "ME 2208 L (Theory of Mechanisms and Machines) (E-CR14)",
    "Lunch",
    "ME 2204 L (Transport Phenomena) (E-CR14)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CM",
    "FREE",
    "MA2209 L (Number theory and Cryptography) (E-CR2)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "MA2212 L  (Functional Analysis ) (E-CR2)",
    "MA2210 L (Optimization Techniques) (E-CR2)",
    "Lunch",
    "MA2213 L (Stochastic Process ) (E-CR2)",
    "MA2211  L (Computer Organization) (E-CR2)",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "HS 2203 T (French - IV) (E-CR9)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "HS 2203 T (French - IV) (E-CR11)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CE",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "FREE",
    "CE 2204 L (Engineering Surveying) (E-CR8)",
    "CE 2205 L(Fluid Mechanics) (E-CR8)",
    "CE 2203 T (E-CR8)",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "CE 2203 L (Mechanics of Materials) (E-CR8)",
  ],
  [
    "CS1",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "FREE",
  ],
  [
    "CS2",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS3",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "EE",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "EE 2201 L (Digital Electronics) (E-CR12)",
    "EE 2203 L (Linear Electronics) (E-CR12)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "EE 2207 L (Electromagnetic Waves) (E-CR12)",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
  ],
  [
    "ECE1",
    "EC 2205 Communication Systems-Lab",
    "EC 2205 Communication Systems-Lab",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ECE2",
    "EC 2203 Digital System Design-Lab",
    "EC 2203 Digital System Design-Lab",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ME",
    "FREE",
    "ME 2204 L (Transport Phenomena) (E-CR14)",
    "ME 2205 L (Manufacturing Processes I) (E-CR14)",
    "ME 2206 L (Mechanics of Solids) (E-CR14)",
    "ME 2208 L (Theory of Mechanisms and Machines) (E-CR14)",
    "Lunch",
    "ME 2204 T (E-CR14)",
    "FREE",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CM",
    "FREE",
    "MA2209 L (Number theory and Cryptography) (E-CR2)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "MA2212 L  (Functional Analysis ) (E-CR2)",
    "MA2210 L (Optimization Techniques) (E-CR2)",
    "Lunch",
    "MA2213 L (Stochastic Process ) (E-CR2)",
    "FREE",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "FREE",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "FREE",
    "FREE",
    "MA2208 L ( Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CE",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "CE 2203 L (Mechanics of Materials) (E-CR8) ",
    "CE 2205 L(Fluid Mechanics) (E-CR8)",
    "CE 2206 L (Concrete Technology) (E-CR8)",
    "CE 2207 L (Construction Technology and Drawing) (E-CR8)",
    "Lunch",
    "CE 2204 Lab ",
    "CE 2204 Lab ",
    "FREE",
  ],
  [
    "CS1",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS2",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "FREE",
  ],
  [
    "CS3",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  L (CS 2201) ((E-LT2)  [till March 7th] / E- LT11)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "CS 2204 L (Theory of Computing) (E-LT1)",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
  ],
  [
    "EE",
    "MA2208 ((E-LT2)  [till March 12th] / E-LT4)",
    "EE 2201 T (E-CR12)",
    "EE 2203 L (Linear Electronics) (E-CR12)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "EE 2207 L (Electromagnetic Waves) (E-CR12)",
    "Lunch",
    "EE 2203 Lab (Linear Electronics)",
    "EE 2203 Lab (Linear Electronics)",
    "FREE",
  ],
  [
    "ECE1",
    "FREE",
    "EC2201 T (E-CR10)",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ECE2",
    "FREE",
    "FREE",
    "CS 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205/EC2201 L (Digital Signal Processing) (E-CR1)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "EC 2205 L (Communication Systems) (E-CR9)",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "ME",
    "FREE",
    "FREE",
    "ME 2205 L (Manufacturing Processes I) (E-CR14)",
    "ME 2206 T (E-CR14)",
    "ME 2208 T (E-CR14)",
    "Lunch",
    "FREE",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CM",
    "FREE",
    "MA2209 L (Number theory and Cryptography) (E-CR2)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "MA2212 L  (Functional Analysis ) (E-CR2)",
    "MA2210 L (Optimization Techniques) (E-CR2)",
    "Lunch",
    "MA2213 L (Stochastic Process ) (E-CR2)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "HS 2203 T (French - IV) (E-CR9)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "AI",
    "FREE",
    "Digital Logic Design and Com. Archi.  L (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2204 L (Theory of Computing) ((E-LT2)  [till March 12th] / E-LT4)",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "HS 2203 T (French - IV) (E-CR11)",
    "FREE",
    "MA2208 L (Numerical Methods) ((E-LT2)  [till March 12th] / E-LT4)",
  ],
  [
    "CE",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "CE 2207 L (Construction Technology and Drawing) (E-CR8)",
    "FREE",
    "CE 2205 LAB (Fluid Mechanics)",
    "CE 2205 LAB (Fluid Mechanics)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "CS1",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi. T (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "FREE",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "CS2",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi. T (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "FREE",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "CS3",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi. T (CS 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "CS 2202 L (Machine Learning and Python) (E-LT1)",
    "CS 2203 L (Artificial & Computational Intelligence) (E-LT1)",
    "FREE",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "EE",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "EE2205  T (E-CR12)",
    "EE 2203 T (E-CR12)",
    "EE 2201 Lab (Digital Electronics)",
    "EE 2201 Lab (Digital Electronics)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "ECE1",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "ECE2",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "ME",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "FREE",
    "FREE",
    "ME 2208 Lab (Theory of Mechanisms and Machines) ",
    "ME 2208 Lab (Theory of Mechanisms and Machines) ",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "CM",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "MA2214 Lab (Programming Workshop) (LH11)",
    "MA2214 Lab (Programming Workshop) (LH11)",
    "FREE",
    "FREE",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "AI",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  T  (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "FREE",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "AI",
    "HS 2201( Design thinking) ((E-LT2)  [till March 12th] / E-LT4)",
    "Digital Logic Design and Com. Archi.  T  (AI 2201) ((E-LT2)  [till March 12th] / E-LT4)",
    "FREE",
    "AI 2203 L (Artificial & Computational Intelligence) (E-LT2)",
    "AI 2202 L (Machine Learning and Python) ((E-LT2)  [till March 12th] / E-LT4)",
    "Lunch",
    "Seminar/Talk",
    "Seminar/Talk",
    "Programming Workshop (Online)- (only for CSE and AI)",
  ],
  [
    "CE",
    "HS 2203 T (French - IV) (E-CR2)",
    "FREE",
    "FREE",
    "CE 2206 Lab (Concrete Technology)",
    "CE 2206 Lab (Concrete Technology)",
    "Lunch",
    "CE 2207 Lab (Construction Technology and Drawing)",
    "CE 2207 Lab (Construction Technology and Drawing)",
    "FREE",
  ],
  [
    "CS1",
    "HS 2203 T (French - IV) (E-CR3)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS2",
    "HS 2203 T (French - IV) (E-CR6)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
  ],
  [
    "CS3",
    "HS 2203 T (French - IV) (E-CR8)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "FREE",
  ],
  [
    "EE",
    "HS 2203 T (French - IV) (E-CR12)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "EE 2207 T (E-CR12)",
    "FREE",
    "FREE",
  ],
  [
    "ECE1",
    "FREE",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "HS 2203 T (French - IV) (E-CR2)",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "ECE2",
    "EC 2201 T (E-CR10)",
    "EC 2203 L (Digital System Design) (E-CR1)",
    "HS 2203 T (French - IV) (E-CR3)",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "ME",
    "FREE",
    "FREE",
    "HS 2203 T (French - IV) (E-CR6)",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CM",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "HS 2203 T (French - IV) (E-CR8)]",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "AI",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "AI",
    "FREE",
    "FREE",
    "FREE",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CE",
    "HS 2203 T (French - IV) (E-CR2)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS1",
    "HS 2203 T (French - IV) (E-CR3)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS2",
    "HS 2203 T (French - IV) (E-CR6)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "CS3",
    "HS 2203 T (French - IV) (E-CR8)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "EE",
    "HS 2203 T (French - IV) (E-CR12)",
    "FREE",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "ECE1",
    "FREE",
    "FREE",
    "HS 2203 T (French - IV) (E-CR2)",
    "FREE",
    "FREE",
    "Lunch",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "FREE",
  ],
  [
    "ECE2",
    "FREE",
    "FREE",
    "HS 2203 T (French - IV) (E-CR3)",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "ME",
    "FREE",
    "FREE",
    "HS 2203 T (French - IV) (E-CR6)",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "Lunch",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "FREE",
  ],
  [
    "CM",
    "HS 2201 Lab ",
    "HS 2201 Lab ",
    "HS 2203 T (French - IV) (E-CR8)]",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "AI",
    "FREE",
    "FREE",
    "FREE",
    "MA2208 Lab (LH12)",
    "MA2208 Lab (LH12)",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
  [
    "AI",
    "MA2208 Lab (LH11)",
    "MA2208 Lab (LH11)",
    "FREE",
    "FREE",
    "FREE",
    "Lunch",
    "FREE",
    "FREE",
    "FREE",
  ],
];

mess = [
  ["WADA", "FREE", "FREE", "MIRCHI BHAJJI"],
  ["WHEAT UPMA", "CHAPATHI", "FREE", "UGGANI"],
  ["FRUIT CAKE", "JEERA RICE", "STEAMED RICE", "TEA"],
  ["TEA", "EGG MASALA CURRY", "ALOO PALAK", "COFFEE"],
  ["COFFEE", "KADAI VEG", "PEAS RICE", "BOOST"],
  ["BOOST", "STEEMED RICE", "RASAM", "MILK"],
  ["MILK", "DONDAKAI CHUTNEY", "DAL MAKHANI", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "RASAM, SAMBAR", "CURD, PICKLE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "MADATHA KHAJA", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["SET DOSA", "FREE", "CHICKEN CORN SOUP", "MINI SAMOSA (Onion & corn stuffing)"],
  ["PEAS UPMA", "POORI", "SWEET CORN SOUP", "BLACK CHANNA"],
  ["CHOCOLATE COOKIES", "CORN PULAO", "SCHEZEWAN EGG FRIED RICE", "TANG"],
  ["TEA", "PUNJABI CHOLE MASALA", "SCHEZEWAN VEG FRIED RICE", "FREE"],
  ["COFFEE", "CABBAGE CARROT PORIYAL", "VEG NOODLES", "FREE"],
  ["BOOST", "STEEMED RICE", "EGG NOODLES", "FREE"],
  ["MILK", "DOSAKAI MUKKALA  CHUTNEY", "FRUIT CUSTARD", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "PALAKURA PAPPU", "DAL ,RASAM", "FREE"],
  ["BOLIED  EGG", "RASAM", "CURD RICE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "RASAM", "FREE"],
  ["GINGER CHUTNEY", "KALA JAMUN", "HOT GARLIC SAUSE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["MYSORE BONDA", "FREE", "PULKA", "PAV BHAJI"],
  [
    "HOT PONGAL",
    "PULKA RUMALI ROTI",
    "SAMBAR RICE WITH BOONDHI",
    "BOILED PEANUTS",
  ],
  ["BREAD BUTTER JAM", "ANDHRA CHICKEN", "RAJMA MASALA", "BUTTER MILK"],
  ["TEA", "STEAMED RICE", "STEAMED RICE", "FREE"],
  ["COFFEE", "BAGARA RICE", "DAL TADKA", "FREE"],
  ["BOOST", "PANEER BUTTER MASALA", "FREE", "FREE"],
  ["MILK", "SAMBAR", "FREE", "FREE"],
  [
    "CORN FLAKES/CHOCOS(ALTERNATE DAYS)",
    "TOMATO RASAM",
    "CURD RICE WITH PROMAGRANATE",
    "FREE",
  ],
  ["COCONUT CHUTNEY SAMBAR", "CURD,  PICKLE.", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "SAGGU BIYAM PAYASAM", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["ONION UTHAPPAM", "FREE", "KULCHA/BUTTERNAAN", "RAGADA PAPIDI"],
  ["VEG UPMA", "CHAPATHI", "MUTTER PANNER", "BHEL POORI"],
  ["STRAWBERRY MUFFINS", "CHINTHAPANDU PULIHORA", "FREE", "TEA"],
  ["TEA", "ALOO METHI CURRY", "STEAMED RICE", "COFFEE"],
  ["COFFEE", "BRINJAL GREEN PEAS DRY CURRY", "DAL MAKANI", "BOOST"],
  ["BOOST", "STEEMED RICE", "RASAM/SAMBAR", "MILK"],
  ["MILK", "TOMATO KOTHIMERA CHUTNEY", "CURD/PICKLE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "MUDHAPAPPU", "CUT FRUITS", "FREE"],
  ["BOLIED  EGG", "MAJJIGACHARU", "FREE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "FREE", "FREE"],
  ["FREE", "MAL POORI", "FREE", "FREE"],
  ["FREE", "TANDOORI SALAD", "FREE", "FREE"],
  ["POORI", "FREE", "PULKA\nVEG PULAO", "PIZZA"],
  ["TOMATO BATH", "PULKA", "FREE", "PALLI PAKODI"],
  ["BROWNIE", "EGG BURJI", "FREE", "TEA"],
  ["TEA", "FREE", "3 IN 1 SALAN", "LEMONADE"],
  ["COFFEE", "MUTTER TOMATO KOTHIMEER", "VEG DALCHA", "FREE"],
  ["BOOST", "STEEMED RICE", "STEAMED RICE", "FREE"],
  ["MILK", "FREE", "RAITA", "FREE"],
  [
    "CORN FLAKES/CHOCOS(ALTERNATE DAYS)",
    "SAMBAR",
    "CURD RICE WITH PROMAGRANATE",
    "FREE",
  ],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["BESAN CURRY", "MOTHICHOOR LADDO", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["ALOO PAROTA", "FREE", "CHAPATHI", "MAGGIE"],
  ["VEG UPMA", "CHAPATHI", "BEERYAKAYA CHENNA CURRY", "SPROUTS"],
  ["BREAD ,BUTTER, JAM", "GREEN PEAS PULAO", "DAL FRY", "TEA"],
  ["TEA", "DUM ALOO BANARAS", "TOMATO PULAO", "COFFEE"],
  ["COFFEE", "BENDI DO PYASSA, THOTAKOORA DAL", "STEAMED RICE", "BOOST"],
  ["BOOST", "STEEMED RICE", "CURD", "MILK"],
  ["MILK", "GONGURA CHUTNEY", "FREE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "MAJJIGA CHARU", "FREE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "ANNAMAYYA LADOO", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["DOSA(KARAM,MASALA,PLAIN)", "KEERA,ONION AND LEMON", "WADA", "PANIPOORI"],
  ["VEG UPMA", "PULKA", "VEG UPMA", "DAHI POORI"],
  ["FREE", "CHICKEN BIRYANI", "STEAMED RICE", "TANG"],
  ["TEA", "MUTTER PANEER", "BREAKFAST SAMBAR", "FREE"],
  ["COFFEE", "VEG DUM BIRYANI", "COCONUT CHUTNEY/ KARAM", "FREE"],
  ["BOOST", "STEEMED RICE", "DAL", "FREE"],
  ["MILK", "MIRCHI KA SALAN", "CURD RICE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "RASAM,SAMBAR", "CUT FRUITS", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "FREE", "FREE"],
  ["GINGER CHUTNEY", "COOL DRINKS", "FREE", "FREE"],
];
