tt = [
  ["A1","CS L (E-LT3)","BIOLOGY L  (for CSE)(ONLINE)  For CM first 7 weeks BIOLOGY (ONLINE) and later 7 weeks CH1202+ CH1204 (E-CR16)","DISC MATH L (E-LT3)","MATH (E-LT3)","LUNCH","CS T (E-CR10)","FREE","PHYSICS P","PHYSICS P"],
  ["A2","CS L (E-LT3)","BIOLOGY L  (for CSE)(ONLINE)  For CM first 7 weeks BIOLOGY (ONLINE) and later 7 weeks CH1202+ CH1204 (E-CR16)","DISC MATH L (E-LT3)","MATH (E-LT3)","LUNCH","CS T (E-CR14)","FREE","FREE","FREE"],
  ["A3","CS L (E-LT3)","BIOLOGY L  (for CSE)(ONLINE)  For CM first 7 weeks BIOLOGY (ONLINE) and later 7 weeks CH1202+ CH1204 (E-CR16)","DISC MATH L (E-LT3)","MATH (E-LT3)","LUNCH","CS T (E-CR16)","FREE","FREE","FREE"],
  ["A4","CS L (E-LT3)","BIOLOGY L  (for CSE)(ONLINE)  For CM first 7 weeks BIOLOGY (ONLINE) and later 7 weeks CH1202+ CH1204 (E-CR16)","DISC MATH L (E-LT3)","MATH (E-LT3)","LUNCH","PHYSICS P","PHYSICS P","CS T (E-CR10)","FREE"],
  ["A5","CS L (E-LT3)","BIOLOGY L  (for CSE)(ONLINE)  For CM first 7 weeks BIOLOGY (ONLINE) and later 7 weeks CH1202+ CH1204 (E-CR16)","DISC MATH L (E-LT3)","MATH (E-LT3)","LUNCH","CS T (E-CR8)","MATH (T) (E-CR10)","(Workshop Practice)","(Workshop Practice)"],
  ["A6","CS T (E-CR7)","CH 1202 L (E-CR1)","HS 1203 T (E-CR7)","EE1202 L (E-CR9)","LUNCH","MATH (E-LT3)","CS (E-LT3)","PHYSICS T (E-CR11)","FREE"],
  ["A7","CS T (E-CR9)","BIOLOGY L (ONLINE)","FREE","MATH (T) (E-CR10)","LUNCH","MATH (E-LT3)","CS (E-LT3)","AI 1202 L (E-LT1)","FREE"],
  ["A8","CS T (E-CR11)","BIOLOGY L (ONLINE)","FREE","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","AI 1202 L (E-LT1)","FREE"],
  ["A9","CS T (E-CR8)","BIOLOGY L (ONLINE)","FREE","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","AI 1202 L (E-LT1)","MATH (T) (E-CR10)"],
  ["A10","CS T (E-CR10)","CH 1202 L (E-CR1)/ MT 1201 L (only for MT) (E-CR16)","MATH (T) (E-CR10)","CE 1202 L (only for CE) (E-CR16)","LUNCH","MATH (E-LT3)","CS (E-LT3)","CH 1202 P -I  (except MT)","CH 1202 P -I  (except MT)"],
  ["A1","HS 1203 T (E-CR8) ","BIOLOGY L (ONLINE)","DISC MATH L (E-LT3)","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","FREE","FREE"],
  ["A2","HS 1203 T (E-CR10) ","BIOLOGY L (ONLINE)","DISC MATH L (E-LT3)","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","PHYSICS P","PHYSICS P"],
  ["A3","HS 1203 T (E-CR12) ","BIOLOGY L (ONLINE)","DISC MATH L (E-LT3)","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","FREE","FREE"],
  ["A4","HS 1203 T (E-CR14) ","BIOLOGY L (ONLINE)","DISC MATH L (E-LT3)","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","FREE","FREE"],
  ["A5","CH 1204 (only for CM) (E-CR16)","BIOLOGY L (ONLINE)","DISC MATH L (E-LT3)","FREE","LUNCH","MATH (E-LT3)","CS (E-LT3)","CS P","CS P"],
  ["A6","CS (E-LT3)","CH 1202 L (E-CR1)","FREE","MATH (E-LT3)","LUNCH","CS P","CS P","(Workshop Practice)","(Workshop Practice)"],
  ["A7","CS (E-LT3)","BIOLOGY L (ONLINE)","FREE","MATH (E-LT3)","LUNCH","PHYSICS P","PHYSICS P","AI 1202 L (E-LT1)","HS 1203 T (E-CR7) "],
  ["A8","CS (E-LT3)","BIOLOGY L (ONLINE)","FREE","MATH (E-LT3)","LUNCH","FREE","FREE","AI 1202 L (E-LT1)","HS 1203 T (E-CR11) "],
  ["A9","CS (E-LT3)","BIOLOGY L (ONLINE)","FREE","MATH (E-LT3)","LUNCH","FREE","FREE","AI 1202 L (E-LT1)","HS 1203 T (E-CR10) "],
  ["A10","CS (E-LT3)","CH 1202 L (E-CR1)/ MT 1201 L (only for MT) (E-CR16)","FREE","MATH (E-LT3)","LUNCH","CE 1202 L (only for CE) (E-CR16)","CH 1202 P -II  (except MT)","CH 1202 P -II  (except MT)","HS 1203 T (E-CR16) "],
  ["A1","PHYSICS L (E-LT3)","BIOLOGY L (ONLINE)","MATH (E-LT3)","PHYSICS T (E-CR6)","LUNCH","FREE","MATH (T) (E-CR6)","FREE","FREE"],
  ["A2","PHYSICS L (E-LT3)","BIOLOGY L (ONLINE)","MATH (E-LT3)","FREE","LUNCH","PHYSICS T (E-CR10)","MATH (T) (E-CR14)","FREE","FREE"],
  ["A3","PHYSICS L (E-LT3)","BIOLOGY L (ONLINE)","MATH (E-LT3)","PHYSICS T (E-CR16)","LUNCH","FREE","MATH (T) (E-CR16)","PHYSICS P","PHYSICS P"],
  ["A4","PHYSICS L (E-LT3)","BIOLOGY L (ONLINE)","MATH (E-LT3)","PHYSICS T (E-CR7)","LUNCH","FREE","FREE","FREE","FREE"],
  ["A5","PHYSICS L (E-LT3)","BIOLOGY L (ONLINE)","MATH (E-LT3)","PHYSICS T (E-CR9)","LUNCH","PHYSICS P","PHYSICS P","CH 1204 (only for CM) (E-CR16)","HS 1203 T (E-CR10)"],
  ["A6","FREE","ME 1201 L (E-CR7)","MATH (T) (E-CR2)","PHYSICS L (E-LT3)","LUNCH","MATH L (E-LT3)","ME 1201  T (Group1 - E-CR8, Group 2 - E-CR10)","CH 1202 P-I","CH 1202 P-I"],
  ["A7","FREE","BIOLOGY L (ONLINE)","HS 1203 T (E-CR7) ","PHYSICS L (E-LT3)","LUNCH","MATH L (E-LT3)","AI 1203 L (E-LT1)","FREE","FREE"],
  ["A8","MATH (T) (E-CR10)","BIOLOGY L (ONLINE)","HS 1203 T (E-CR9) ","PHYSICS L (E-LT3)","LUNCH","MATH L (E-LT3)","AI 1203 L (E-LT1)","FREE","PHYSICS T (E-CR16)"],
  ["A9","FREE","BIOLOGY L (ONLINE)","HS 1203 T (E-CR10) ","PHYSICS L (E-LT3)","LUNCH","MATH L (E-LT3)","AI 1203 L (E-LT1)","FREE","PHYSICS T (E-CR7)"],
  ["A10","MT 1201 L (only for MT) (E-CR16)","ME 1201 L (E-CR7)","HS 1203 T (E-CR16) ","PHYSICS L (E-LT3)","LUNCH","MATH L (E-LT3)","ME 1201  T (Group 3 - E-CR12)","FREE","PHYSICS T (E-CR9)"],
  ["A1","FREE","HS 1203 T (E-CR7) ","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A2","FREE","HS 1203 T (E-CR9) ","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A3","FREE","HS 1203 T (E-CR11) ","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A4","FREE","HS 1203 T (E-CR13) ","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A5","FREE","CH 1204 (only for CM) (E-CR16)","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A6","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","ME 1201 L (E-CR7)","EE1202 L (E-CR9)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A7","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","PHYSICS T (E-CR6)","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A8","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","FREE","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A9","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","FREE","FREE","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A10","PHYSICS L (E-LT3)","HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (E-LT3)","ME 1201 L (E-CR7)","FREE","LUNCH","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc ","Seminars / Workshops etc "],
  ["A1","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A2","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A3","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A4","FREE","FREE","FREE","MATH (T) (E-CR14)","LUNCH","FREE","FREE","FREE","FREE"],
  ["A5","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","HS 1203 T (E-CR10) "],
  ["A6","EE1202 P","EE1202 P","PHYSICS P","PHYSICS P","LUNCH","CH 1202 P-II","CH 1202 P-II","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","HS 1203 T (E-CR7) "],
  ["A7","FREE","FREE","FREE","FREE","LUNCH","(Workshop Practice)","(Workshop Practice)","CS P","CS P"],
  ["A8","PHYSICS P","PHYSICS P","FREE","FREE","LUNCH","CS P","CS P","(Workshop Practice)","(Workshop Practice)"],
  ["A9","(Workshop Practice)","(Workshop Practice)","CS P","CS P","LUNCH","PHYSICS P","PHYSICS P","FREE","FREE"],
  ["A10","CS P","CS P","(Workshop Practice)","(Workshop Practice)","LUNCH","ME 1210 L  (Only for ME/MT) (E-CR10)","FREE","PHYSICS P","PHYSICS P"],
  ["A1","CS P","CS P","(Workshop Practice)","(Workshop Practice)","LUNCH","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","FREE","FREE"],
  ["A2","(Workshop Practice)","(Workshop Practice)","CS P","CS P","LUNCH","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","FREE","FREE"],
  ["A3","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","FREE","FREE","LUNCH","CS P","CS P","(Workshop Practice)","(Workshop Practice)"],
  ["A4","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","FREE","FREE","LUNCH","(Workshop Practice)","(Workshop Practice)","CS P","CS P"],
  ["A5","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A6","FREE","EE1202 T (E-CR13)","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A7","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A8","FREE","FREE","FREE","FREE","LUNCH","FREE","FREE","FREE","FREE"],
  ["A9","FREE","FREE","FREE","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","LUNCH","FREE","FREE","FREE","FREE"],
  ["A10","ME 1210 P (Only for ME/MT) (LH12)","ME 1210 P (Only for ME/MT) (LH12)","ME 1210 P (Only for ME/MT) (LH12)","HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (E-CR9)","LUNCH","FREE","FREE","FREE","FREE"]
];