tt = [[
  "A1",
  "CS LECTURE | CONVO",
  "BI LECTURE",
  "CS LECTURE | CONVO",
  "MA 1202 (LT12)",
  "LUNCH",
  "CS 1201 T (CR5)",
  "FREE",
  "PH1202 P",
  "PH1202 P",
  "A1"
],
[
  "A2",
  "CS LECTURE | CONVO",
  "BI LECTURE",
  "CS LECTURE | CONVO",
  "MA 1202 (LT12)",
  "LUNCH",
  "CS 1201 T (CR7)",
  "FREE",
  "FREE",
  "FREE",
  "A2"
],
[
  "A3",
  "CS LECTURE | CONVO",
  "BI LECTURE",
  "CS LECTURE | CONVO",
  "MA 1202 (LT12)",
  "LUNCH",
  "CS 1201 T (CR8)",
  "FREE",
  "FREE",
  "FREE",
  "A3"
],
[
  "A4",
  "CS LECTURE | CONVO",
  "BI LECTURE",
  "CS LECTURE | CONVO",
  "MA 1202 (LT12)",
  "LUNCH",
  "PH1202 P",
  "PH1202 P",
  "CS 1201 T (CR5)",
  "FREE",
  "A4"
],
[
  "A5",
  "CS LECTURE | CONVO",
  "BI LECTURE",
  "CS LECTURE | CONVO",
  "MA 1202 (LT12)",
  "LUNCH",
  "CS 1201 T (CR4)",
  "MA 1202 (T) (CR5)",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "A5"
],
[
  "A6",
  "CS 1201 T (LT6)",
  "CH 1202 L (LT3)",
  "HS 1203 T (LT6)",
  "EE1202 L (LT7)",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "PH1202 T (LT8)",
  "FREE",
  "A6"
],
[
  "A7",
  "CS 1201 T (LT7)",
  "BI 1201 L (ONLINE)",
  "FREE",
  "MA 1202 (T) (CR5)",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "AI 1202 L (LT1)",
  "FREE",
  "A7"
],
[
  "A8",
  "CS 1201 T (LT8)",
  "BI 1201 L (ONLINE)",
  "FREE",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "AI 1202 L (LT1)",
  "FREE",
  "A8"
],
[
  "A9",
  "CS 1201 T (CR4)",
  "BI 1201 L (ONLINE)",
  "FREE",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "AI 1202 L (LT1)",
  "MA 1202 (T) (CR5)",
  "A9"
],
[
  "A10",
  "CS 1201 T (CR5)",
  "CH 1202 L (LT3)/\r\nMT 1201 L (only for MT) (CR8)",
  "MA 1202 (T) (CR5)",
  "CE 1202 L (only for CE) (CR8)",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "CH 1202 P -I  (except MT)",
  "CH 1202 P -I  (except MT)",
  "A10"
],
[
  "A1",
  "HS 1203 T (CR4)\r\n",
  "BI 1201 L (ONLINE)",
  "CS LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "FREE",
  "FREE",
  "A1"
],
[
  "A2",
  "HS 1203 T (CR5)\r\n",
  "BI 1201 L (ONLINE)",
  "CS LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "PH1202 P",
  "PH1202 P",
  "A2"
],
[
  "A3",
  "HS 1203 T (CR6)\r\n",
  "BI 1201 L (ONLINE)",
  "CS LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "FREE",
  "FREE",
  "A3"
],
[
  "A4",
  "HS 1203 T (CR7)\r\n",
  "BI 1201 L (ONLINE)",
  "CS LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "FREE",
  "FREE",
  "A4"
],
[
  "A5",
  "CH 1204 (only for CM) (CR8)",
  "BI 1201 L (ONLINE)",
  "CS LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "MA LECTURE | CONVO",
  "CS LECTURE | CONVO",
  "CS 1201 P",
  "CS 1201 P",
  "A5"
],
[
  "A6",
  "CS LECTURE | CONVO",
  "CH 1202 L (LT3)",
  "FREE",
  "MA LECTURE | CONVO",
  "LUNCH",
  "CS 1201 P",
  "CS 1201 P",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "A6"
],
[
  "A7",
  "CS LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "FREE",
  "MA LECTURE | CONVO",
  "LUNCH",
  "PH1202 P",
  "PH1202 P",
  "AI 1202 L (LT1)",
  "HS 1203 T (LT6)\r\n",
  "A7"
],
[
  "A8",
  "CS LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "FREE",
  "MA LECTURE | CONVO",
  "LUNCH",
  "FREE",
  "FREE",
  "AI 1202 L (LT1)",
  "HS 1203 T (LT8)\r\n",
  "A8"
],
[
  "A9",
  "CS LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "FREE",
  "MA LECTURE | CONVO",
  "LUNCH",
  "FREE",
  "FREE",
  "AI 1202 L (LT1)",
  "HS 1203 T (CR5)\r\n",
  "A9"
],
[
  "A10",
  "CS LECTURE | CONVO",
  "CH 1202 L (LT3)/\r\nMT 1201 L (only for MT) (CR8)",
  "FREE",
  "MA LECTURE | CONVO",
  "LUNCH",
  "CE 1202 L (only for CE) (CR8)",
  "CH 1202 P -II  (except MT)",
  "CH 1202 P -II  (except MT)",
  "HS 1203 T (CR8)\r\n",
  "A10"
],
[
  "A1",
  "PH LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "MA LECTURE | CONVO",
  "PH1202 T (CR3)",
  "LUNCH",
  "FREE",
  "MA 1202 (T) (CR3)",
  "FREE",
  "FREE",
  "A1"
],
[
  "A2",
  "PH LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "MA LECTURE | CONVO",
  "FREE",
  "LUNCH",
  "PH1202 T (CR5)",
  "MA 1202 (T) (CR7)",
  "FREE",
  "FREE",
  "A2"
],
[
  "A3",
  "PH LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "MA LECTURE | CONVO",
  "PH1202 T (CR8)",
  "LUNCH",
  "FREE",
  "MA 1202 (T) (CR8)",
  "PH1202 P",
  "PH1202 P",
  "A3"
],
[
  "A4",
  "PH LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "MA LECTURE | CONVO",
  "PH1202 T (LT6)",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A4"
],
[
  "A5",
  "PH LECTURE | CONVO",
  "BI 1201 L (ONLINE)",
  "MA LECTURE | CONVO",
  "PH1202 T (LT7)",
  "LUNCH",
  "PH1202 P",
  "PH1202 P",
  "CH 1204 (only for CM) (CR8)",
  "HS 1203 T (CR5)",
  "A5"
],
[
  "A6",
  "FREE",
  "ME 1201 L (LT6)",
  "MA 1202 (T) (CR1)",
  "PH LECTURE | CONVO",
  "LUNCH",
  "MA 1202 L (Convention Center [till March 2nd] / E-LT12)",
  "ME 1201  T (Group1 - CR4, Group 2 - CR5)",
  "CH 1202 P-I",
  "CH 1202 P-I",
  "A6"
],
[
  "A7",
  "FREE",
  "BI 1201 L (ONLINE)",
  "HS 1203 T (LT6)\r\n",
  "PH LECTURE | CONVO",
  "LUNCH",
  "MA 1202 L (Convention Center [till March 2nd] / E-LT12)",
  "AI 1203 L (LT1)",
  "FREE",
  "FREE",
  "A7"
],
[
  "A8",
  "MA 1202 (T) (CR5)",
  "BI 1201 L (ONLINE)",
  "HS 1203 T (LT7)\r\n",
  "PH LECTURE | CONVO",
  "LUNCH",
  "MA 1202 L (Convention Center [till March 2nd] / E-LT12)",
  "AI 1203 L (LT1)",
  "FREE",
  "PH1202 T (CR8)",
  "A8"
],
[
  "A9",
  "FREE",
  "BI 1201 L (ONLINE)",
  "HS 1203 T (CR5)\r\n",
  "PH LECTURE | CONVO",
  "LUNCH",
  "MA 1202 L (Convention Center [till March 2nd] / E-LT12)",
  "AI 1203 L (LT1)",
  "FREE",
  "PH1202 T (LT6)",
  "A9"
],
[
  "A10",
  "MT 1201 L (only for MT) (CR8)",
  "ME 1201 L (LT6)",
  "HS 1203 T (CR8)\r\n",
  "PH LECTURE | CONVO",
  "LUNCH",
  "MA 1202 L (Convention Center [till March 2nd] / E-LT12)",
  "ME 1201  T (Group 3 - CR6)",
  "FREE",
  "PH1202 T (LT7)",
  "A10"
],
[
  "A1",
  "FREE",
  "HS 1203 T (LT6)\r\n",
  "PH LECTURE | CONVO",
  "HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (Convention Center [till March 2nd] / E-LT12)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A2",
  "FREE",
  "HS 1203 T (LT7)\r\n",
  "PH LECTURE | CONVO",
  "HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (Convention Center [till March 2nd] / E-LT12)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A3",
  "FREE",
  "HS 1203 T (LT8)\r\n",
  "PH LECTURE | CONVO",
  "HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (Convention Center [till March 2nd] / E-LT12)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A4",
  "FREE",
  "HS 1203 T (LT9)\r\n",
  "PH LECTURE | CONVO",
  "HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (Convention Center [till March 2nd] / E-LT12)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A5",
  "FREE",
  "CH 1204 (only for CM) (CR8)",
  "PH LECTURE | CONVO",
  "HS 1202 (first 7 weeks) /HS1201 (second 7 weeks) (Convention Center [till March 2nd] / E-LT12)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A6",
  "PH LECTURE | CONVO",
  "ETHICS | CONVO",
  "ME 1201 L (LT6)",
  "EE1202 L (LT7)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A7",
  "PH LECTURE | CONVO",
  "ETHICS | CONVO",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "PH1202 T (CR3)",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A8",
  "PH LECTURE | CONVO",
  "ETHICS | CONVO",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "FREE",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A9",
  "PH LECTURE | CONVO",
  "ETHICS | CONVO",
  "FREE",
  "FREE",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A10",
  "PH LECTURE | CONVO",
  "ETHICS | CONVO",
  "ME 1201 L (LT6)",
  "FREE",
  "LUNCH",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc ",
  "Seminars / Workshops etc "
],
[
  "A1",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A1"
],
[
  "A2",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A2"
],
[
  "A3",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A3"
],
[
  "A4",
  "FREE",
  "FREE",
  "FREE",
  "MA 1202 (T) (CR7)",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A4"
],
[
  "A5",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "HS 1203 T (CR5)\r\n",
  "A5"
],
[
  "A6",
  "EE1202 P",
  "EE1202 P",
  "PH1202 P",
  "PH1202 P",
  "LUNCH",
  "CH 1202 P-II",
  "CH 1202 P-II",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "HS 1203 T (LT6)\r\n",
  "A6"
],
[
  "A7",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "CS 1201 P",
  "CS 1201 P",
  "A7"
],
[
  "A8",
  "PH1202 P",
  "PH1202 P",
  "FREE",
  "FREE",
  "LUNCH",
  "CS 1201 P",
  "CS 1201 P",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "A8"
],
[
  "A9",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "CS 1201 P",
  "CS 1201 P",
  "LUNCH",
  "PH1202 P",
  "PH1202 P",
  "FREE",
  "FREE",
  "A9"
],
[
  "A10",
  "CS 1201 P",
  "CS 1201 P",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "LUNCH",
  "ME 1210 L  (Only for ME/MT) (CR5)",
  "FREE",
  "PH1202 P",
  "PH1202 P",
  "A10"
],
[
  "A1",
  "CS 1201 P",
  "CS 1201 P",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "LUNCH",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "FREE",
  "FREE",
  "A1"
],
[
  "A2",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "CS 1201 P",
  "CS 1201 P",
  "LUNCH",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "FREE",
  "FREE",
  "A2"
],
[
  "A3",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "FREE",
  "FREE",
  "LUNCH",
  "CS 1201 P",
  "CS 1201 P",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "A3"
],
[
  "A4",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "FREE",
  "FREE",
  "LUNCH",
  "ME 1202 (Workshop Practice)",
  "ME 1202 (Workshop Practice)",
  "CS 1201 P",
  "CS 1201 P",
  "A4"
],
[
  "A5",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A5"
],
[
  "A6",
  "FREE",
  "EE1202 T (LT9)",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A6"
],
[
  "A7",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A7"
],
[
  "A8",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A8"
],
[
  "A9",
  "FREE",
  "FREE",
  "FREE",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A9"
],
[
  "A10",
  "ME 1210 P (Only for ME/MT) (LH12)",
  "ME 1210 P (Only for ME/MT) (LH12)",
  "ME 1210 P (Only for ME/MT) (LH12)",
  "HS 1202 T(first 7 weeks) /HS1201 T (second 7 weeks) (LT7)",
  "LUNCH",
  "FREE",
  "FREE",
  "FREE",
  "FREE",
  "A10"
]];